name: job_search
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Base
  html_editor_enhanced: ^2.5.1
  awesome_snackbar_content: ^0.1.3
  cupertino_icons: ^1.0.3
  nb_utils: 6.0.0
  intl: ^0.18.0
  dropdown_button2: ^2.3.7
  dropdown_search: ^5.0.6
  shimmer: ^3.0.0
  flutter_widget_from_html: ^0.10.3
  path_provider: ^2.1.0
  flutter_vector_icons: ^1.0.0
  google_fonts: ^5.1.0
  cached_network_image: ^3.1.0
  galleryimage: ^2.0.1
  get: ^4.6.5
  image_picker: ^1.0.1
  file_picker: ^5.3.3
  # STATE MANAGEMENT
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.0.2
  build_runner: ^2.1.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - images/jobSearch/
    - images/jobSearch/gif/

